# Generated by Django 5.0 on 2023-12-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lesson',
            field=models.ManyToManyField(related_name='students', to='app1.lesson'),
        ),
    ]
